// Code generated by github.com/worldiety/template-go
// do not modify, the Build* variables are set at build time using ldflags

package wdydoc

var BuildGitCommit = "unknown"
var BuildGitBranch = "unknown"
var BuildHost = "unknown"
